using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VRBuilder.Catalog.Generator;

/// <summary>
/// Emits a module initializer that registers every concrete class of the compiling assembly into
/// VRBuilder.Core.Utils.TypeRegistry, keyed by every base class and interface it implements.
/// This is the AOT-safe replacement for "find all types assignable to X" style reflection
/// (Assembly.GetTypes + IsAssignableFrom), which does not work once an app is trimmed or
/// NativeAOT-published: each assembly self-registers at load time instead of being scanned later.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class TypeRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => BuildDescriptor(ctx, ct))
            .Where(static d => d != null);

        var registrations = candidates.Collect();

        context.RegisterSourceOutput(registrations, static (spc, descriptors) =>
            Emit(spc, descriptors.Where(d => d != null).Select(d => d!)));
    }

    private static Descriptor BuildDescriptor(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var classSymbol = context.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)context.Node, ct)
            as INamedTypeSymbol;
        if (classSymbol == null)
        {
            return null;
        }

        if (classSymbol.IsAbstract || classSymbol.IsGenericType || classSymbol.TypeKind != TypeKind.Class)
        {
            return null;
        }

        // Accessible-by-name types only, and no types nested in a generic type (their closed form
        // cannot be named with a plain typeof() from generated code).
        for (var symbol = (ISymbol)classSymbol; symbol != null; symbol = symbol.ContainingType)
        {
            if (symbol.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
            {
                return null;
            }

            if (symbol is INamedTypeSymbol { IsGenericType: true } && symbol != classSymbol)
            {
                return null;
            }
        }

        var assignableTypes = new List<string>();
        var seen = new HashSet<string>();

        void AddIfNew(ITypeSymbol type)
        {
            var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (seen.Add(name))
            {
                assignableTypes.Add(name);
            }
        }

        for (var baseType = classSymbol.BaseType; baseType != null && baseType.SpecialType != SpecialType.System_Object; baseType = baseType.BaseType)
        {
            AddIfNew(baseType);
        }

        foreach (var iface in classSymbol.AllInterfaces)
        {
            AddIfNew(iface);
        }

        if (assignableTypes.Count == 0)
        {
            return null;
        }

        var typeName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return new Descriptor(typeName, assignableTypes.ToArray());
    }

    private static void Emit(SourceProductionContext context, IEnumerable<Descriptor> descriptors)
    {
        var entries = descriptors.OrderBy(d => d.TypeName, System.StringComparer.Ordinal).ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("namespace VRBuilder.Core.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class TypeRegistryBootstrap");
        builder.AppendLine("    {");
        builder.AppendLine("        [System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void Register()");
        builder.AppendLine("        {");

        foreach (var entry in entries)
        {
            var assignable = string.Join(", ", entry.AssignableTypes.Select(t => $"typeof({t})"));
            builder.AppendLine($"            global::VRBuilder.Core.Utils.TypeRegistry.Register(typeof({entry.TypeName}), {assignable});");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("TypeRegistryBootstrap.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private sealed class Descriptor
    {
        public Descriptor(string typeName, string[] assignableTypes)
        {
            TypeName = typeName;
            AssignableTypes = assignableTypes;
        }

        public string TypeName { get; }
        public string[] AssignableTypes { get; }

        public override bool Equals(object obj) =>
            obj is Descriptor other && TypeName == other.TypeName && AssignableTypes.SequenceEqual(other.AssignableTypes);

        public override int GetHashCode() => TypeName.GetHashCode();
    }
}
