<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>VRBuilder.Core.Serialization.NewtonsoftJson</RootNamespace>
    <AssemblyName>VRBuilder.Core.Serialization.Newtonsoft</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin/**" />
    <Compile Remove="obj/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../VRBuilder.Core.csproj" />
  </ItemGroup>

</Project>
